flowchart TB
    A["Vist site"] --> B("Sign in through formbar")
    B --> C{"If Formbar account exists/logged in"}
    C --> D["True"] & E["False"]
    D --> I["Make pet"]
    I --> F["hunger/joy decrease"]
    F --> G["Feed/joy pet"]
    G --> F
    E --> H["make formbar account/login"]
    H --> C